# specify all the services you want to spin up (docker-compose up -d)
services:
  # database service backend will be connecting to 
  db:
    image: postgres:16
    container_name: postgres_db

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    # map local machine port to container port
    ports:
      - "5433:5432"
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
# persist DB b/w restarts
volumes:
  postgres_data: