"""changed filename col name to file_name for standardization

Revision ID: 3c116f73c075
Revises: ade409fb0fa3
Create Date: 2026-05-29 12:20:09.777423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c116f73c075'
down_revision: Union[str, Sequence[str], None] = 'ade409fb0fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_name', sa.String(), nullable=False))
    op.drop_column('documents', 'filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('documents', 'file_name')
    # ### end Alembic commands ###
